### ISSUE TITLE
addScreenCapture not working in ExtentX

### ISSUE THREAD

**Issue by fowadhamza** [anshooarora/extentx#35] opened 2016-07-18 12:48 UTC
hi Anshoo,

I am not getting the addScreenCapture to work in ExentX.It is working fine in the previous version of Extent though..

![image](https://cloud.githubusercontent.com/assets/13636673/16915070/551fa034-4d13-11e6-9791-4891b9170063.png)

![image](https://cloud.githubusercontent.com/assets/13636673/16915171/e435a58e-4d13-11e6-8fb0-f500ebb4426c.png)

Any idea why this is happening?

**Comment by tvdberk** [comment] 2016-07-18 12:50
duplicate of https://github.com/anshooarora/extentx/issues/9?

**Closed** 2016-07-28 15:31 UTC
Labels: duplicate
